### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by elzes** [mojohaus/cassandra-maven-plugin#1]
Hi,

Can you please create a release that provides:
https://github.com/mojohaus/cassandra-maven-plugin/commit/c304b3dca74e708005564eab2fe5a7697a40ad94

**Comment by sparhomenko** [comment]
+1. We are currently using a patched version of `cassandra-maven-plugin` hosted in our corporate repository, and a new release on Maven Central with 519ed57 and 7230380 would be appreciated.

**Comment by harishdeshmukh** [comment]
+1

**Comment by olamy** [comment]
I agree but ATM I don't if it's possible to deploy to central with groupId: org.codehaus.mojo? 
@Batmat @khmarbaise @brianf  any ideas?

**Comment by Batmat** [comment]
Now it is, thanks to @khmarbaise who made the move to ossrh,and
@mfriedenhagen for validating it.
Le 22 juil. 2015 1:45 AM, "Olivier Lamy" <notifications@github.com> a
écrit :

**Comment by olamy** [comment]
2.1.7-1 has  been released.
