### ISSUE TITLE
mvn cassandra:start does not keep cassandra process up

### ISSUE THREAD

**Issue by shintasmith** [mojohaus/cassandra-maven-plugin#10]
I am using cassandra-maven-plugin version 2.0.0-1. It is specificly that version because we are still using Cassandra 2.0.x

When I ran this command:
```
mvn cassandra:start -DcassandraDir=/tmp/cassandra
```
I expected it to launch cassandra process and the process should be up and running in the background after the maven command finished. But in my case, it appeared to be running:
```
[INFO] Cassandra cluster "Test Cluster" started.
[INFO] Running /home/shintasmith/src/cassandra/cli/load.script...
[INFO] Connected to: "Test Cluster" on 127.0.0.1/9160
[INFO] Finished /home/shintasmith/src/cassandra/cli/load.script.
[INFO] Cassandra started in 4.0s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
But no cassandra is running. 

It's possible I'm missing something. What do I need to do to get cassandra to run in the background?

**Comment by schuth** [comment]
What about cassandra:run?

**Comment by shintasmith** [comment]
cassandra:run runs Cassandra in the foreground.

**Comment by schuth** [comment]
You will have to perform the stuff you want to do in the build phase after `cassandra:start` (most common use case is the `integration-test` phase).You will have a cassandra instance running, and the running cassandra will then be stopped in the `post-integration-test` phase (goal: `stop`).

I looks like your expectations show the misconception that you will be able to fork out a running process using the cassandra plugin and maven, but this is actually not the case. The plugin provides you a cassandra instance *while* the build is running.

**Comment by shintasmith** [comment]
@schuth ah, gotcha. Yeah, I misunderstood the "running in background" part. Thanks!
