### ISSUE TITLE
Plugin doesnt work with cassandra-all 4.x.x

### ISSUE THREAD

**Issue by Honza-cz** [mojohaus/cassandra-maven-plugin#172]
I tried to use this plugin with cassandra 4.1.3
When running mvn clean install, cassandra refuses to start due to the error:

"10:14:39.349 [main] ERROR org.apache.cassandra.service.CassandraDaemon - Exception encountered during startup: Invalid yaml. Please remove properties [start_rpc, rpc_server_type, rpc_port, thrift_framed_transport_size_in_mb, request_scheduler] from your cassandra.yaml
"

I tried to use plugin configuration::yaml to pass null or empty value to those fields, but it didn't fix error.

`<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cassandra-maven-plugin</artifactId>
    <version>3.7</version> 
    <configuration>
        <yaml></yaml>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>start</goal>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>4.1.3</version>
        </dependency>
    </dependencies>
</plugin>`

**Comment by slachiewicz** [comment]
I've released version 4.0.0 - could You test it?
