### ISSUE TITLE
log4j configuration overridden

### ISSUE THREAD

**Issue by ajs6f** [mojohaus/cassandra-maven-plugin#30]
Currently, this plugin overrides configuration from the  `log4j.configuration` system property. There's no need to do that-- it can be used if it is available and set if not.

**Comment by ajs6f** [comment]
https://github.com/mojohaus/cassandra-maven-plugin/pull/29

**Comment by olamy** [comment]
merged

**Comment by ajs6f** [comment]
Thank you very much @olamy ! Please let me know anything I can do to encourage or help with a release.
