### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:3.6

### ISSUE THREAD

**Issue by ghost** [mojohaus/cassandra-maven-plugin#32]
Hi,

I get this error nodetool.jar not found for flush

On Mac OSX, JDK 11, Maven CLI 3.6.1.

Can you please help me to fix the mistake in my POM setup or conflicting dependencies.

Have the POM section and the errors seen after that below.

Thank you in advance.

=== POM section 

 <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cassandra-maven-plugin</artifactId>
                <version>${cassandra-maven-plugin.version}</version>
                <configuration>
                    <addMainClasspath>true</addMainClasspath>
                    <addTestClasspath>true</addTestClasspath>
                    <rpcPort>19160</rpcPort>
                    <jmxPort>17199</jmxPort>
                    <storagePort>17000</storagePort>
                    <stopPort>18081</stopPort>
                    <script>${basedir}/src/main/deploy/init/cassandra-conf/AerFrameCluster.script</script>
                </configuration>
                <executions>
                    <execution>
                        <id>start-cassandra</id>
                        <goals>
                            <goal>start</goal>
                            <goal>flush</goal>
                            <goal>cleanup</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                    </execution>
                    <execution>
                        <id>stop-cassandra</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <phase>post-integration-test</phase>
                    </execution>
                </executions>
            </plugin>

=====
[DEBUG] First start of Cassandra instance in /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra as it does not exist.
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/bin as it does not exist.
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/conf as it does not exist.
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/data as it does not exist.
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/commitlog as it does not exist.
[DEBUG] Creating directory /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/saved_caches as it does not exist.
[DEBUG] Creating /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/conf/cassandra.yaml
[DEBUG] Creating /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/conf/log4j-server.xml
[DEBUG] Creating /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/conf/log4j-client.xml
[DEBUG] Creating /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/bin/cassandra.jar
[DEBUG] Adding plugin artifact: org.codehaus.mojo:cassandra-maven-plugin to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.mojo:cassandra-maven-plugin to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.cassandra:cassandra-all to the classpath
[DEBUG] Adding plugin dependency artifact: org.xerial.snappy:snappy-java to the classpath
[DEBUG] Adding plugin dependency artifact: net.jpountz.lz4:lz4 to the classpath
[DEBUG] Adding plugin dependency artifact: com.ning:compress-lzf to the classpath
[DEBUG] Adding plugin dependency artifact: com.google.guava:guava to the classpath
[DEBUG] Adding plugin dependency artifact: commons-cli:commons-cli to the classpath
[DEBUG] Adding plugin dependency artifact: commons-codec:commons-codec to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.commons:commons-lang3 to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.commons:commons-math3 to the classpath
[DEBUG] Adding plugin dependency artifact: com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru to the classpath
[DEBUG] Adding plugin dependency artifact: org.antlr:antlr to the classpath
[DEBUG] Adding plugin dependency artifact: org.antlr:ST4 to the classpath
[DEBUG] Adding plugin dependency artifact: org.antlr:antlr-runtime to the classpath
[DEBUG] Adding plugin dependency artifact: org.slf4j:slf4j-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.slf4j:log4j-over-slf4j to the classpath
[DEBUG] Adding plugin dependency artifact: org.slf4j:jcl-over-slf4j to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.jackson:jackson-core-asl to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.jackson:jackson-mapper-asl to the classpath
[DEBUG] Adding plugin dependency artifact: com.googlecode.json-simple:json-simple to the classpath
[DEBUG] Adding plugin dependency artifact: com.boundary:high-scale-lib to the classpath
[DEBUG] Adding plugin dependency artifact: org.yaml:snakeyaml to the classpath
[DEBUG] Adding plugin dependency artifact: org.mindrot:jbcrypt to the classpath
[DEBUG] Adding plugin dependency artifact: io.dropwizard.metrics:metrics-core to the classpath
[DEBUG] Adding plugin dependency artifact: com.addthis.metrics:reporter-config3 to the classpath
[DEBUG] Adding plugin dependency artifact: com.addthis.metrics:reporter-config-base to the classpath
[DEBUG] Adding plugin dependency artifact: org.hibernate:hibernate-validator to the classpath
[DEBUG] Adding plugin dependency artifact: javax.validation:validation-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.jboss.logging:jboss-logging to the classpath
[DEBUG] Adding plugin dependency artifact: com.thinkaurelius.thrift:thrift-server to the classpath
[DEBUG] Adding plugin dependency artifact: com.lmax:disruptor to the classpath
[DEBUG] Adding plugin dependency artifact: com.clearspring.analytics:stream to the classpath
[DEBUG] Adding plugin dependency artifact: it.unimi.dsi:fastutil to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.thrift:libthrift to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.httpcomponents:httpclient to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.httpcomponents:httpcore to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.cassandra:cassandra-thrift to the classpath
[DEBUG] Adding plugin dependency artifact: com.carrotsearch:hppc to the classpath
[DEBUG] Adding plugin dependency artifact: de.jflex:jflex to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.ant:ant to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.ant:ant-launcher to the classpath
[DEBUG] Adding plugin dependency artifact: net.mintern:primitive to the classpath
[DEBUG] Adding plugin dependency artifact: com.github.rholder:snowball-stemmer to the classpath
[DEBUG] Adding plugin dependency artifact: com.googlecode.concurrent-trees:concurrent-trees to the classpath
[DEBUG] Adding plugin dependency artifact: net.java.dev.jna:jna to the classpath
[DEBUG] Adding plugin dependency artifact: com.github.jbellis:jamm to the classpath
[DEBUG] Adding plugin dependency artifact: io.netty:netty-all to the classpath
[DEBUG] Adding plugin dependency artifact: joda-time:joda-time to the classpath
[DEBUG] Adding plugin dependency artifact: org.fusesource:sigar to the classpath
[DEBUG] Adding plugin dependency artifact: org.eclipse.jdt.core.compiler:ecj to the classpath
[DEBUG] Adding plugin dependency artifact: org.caffinitas.ohc:ohc-core to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-project to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-settings to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-profile to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-plugin-registry to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.plexus:plexus-interpolation to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven.shared:maven-filtering to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-monitor to the classpath
[DEBUG] Adding plugin dependency artifact: org.sonatype.plexus:plexus-build-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-model to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-artifact to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-artifact-manager to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-repository-metadata to the classpath
[DEBUG] Adding plugin dependency artifact: backport-util-concurrent:backport-util-concurrent to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-core to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-plugin-parameter-documenter to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven.reporting:maven-reporting-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven.doxia:doxia-sink-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven.doxia:doxia-logging-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-error-diagnostics to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-plugin-descriptor to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.plexus:plexus-interactivity-api to the classpath
[DEBUG] Adding plugin dependency artifact: classworlds:classworlds to the classpath
[DEBUG] Adding plugin dependency artifact: org.sonatype.plexus:plexus-sec-dispatcher to the classpath
[DEBUG] Adding plugin dependency artifact: org.sonatype.plexus:plexus-cipher to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-plugin-api to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.plexus:plexus-utils to the classpath
[DEBUG] Adding plugin dependency artifact: org.codehaus.plexus:plexus-container-default to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.commons:commons-exec to the classpath
[DEBUG] Adding plugin dependency artifact: org.apache.maven:maven-toolchain to the classpath
[DEBUG] Adding plugin dependency artifact: org.cassandraunit:cassandra-unit to the classpath
[DEBUG] Adding plugin dependency artifact: org.hamcrest:hamcrest-all to the classpath
[DEBUG] Adding plugin dependency artifact: com.sun.xml.bind:jaxb-impl to the classpath
[DEBUG] Adding plugin dependency artifact: javax.xml.bind:jaxb-api to the classpath
[DEBUG] Adding plugin dependency artifact: javax.xml.stream:stax-api to the classpath
[DEBUG] Adding plugin dependency artifact: javax.activation:activation to the classpath
[DEBUG] Adding plugin dependency artifact: me.prettyprint:hector-core to the classpath
[DEBUG] Adding plugin dependency artifact: commons-pool:commons-pool to the classpath
[DEBUG] Adding plugin dependency artifact: com.github.stephenc.eaio-uuid:uuid to the classpath
[DEBUG] Adding plugin dependency artifact: com.ecyrd.speed4j:speed4j to the classpath
[DEBUG] Adding plugin dependency artifact: commons-lang:commons-lang to the classpath
[DEBUG] Adding: /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/test-classes to the classpath
[DEBUG] Adding: /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/classes to the classpath
[DEBUG] Executing command line: java -Xmx512m -Dcassandra.storagedir=/Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra -DSTOP.KEY=cassandra-maven-plugin -DSTOP.PORT=18081 -DSTOP.HOST=127.0.0.1 -Dlog4j.configurationFile=file:/Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/conf/log4j-server.xml -Dcom.sun.management.jmxremote=true -DcassandraLogLevel=ERROR -Dcom.sun.management.jmxremote.port=17199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -jar /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/bin/cassandra.jar
[INFO] Waiting for Cassandra to start...
[INFO] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] SLF4J: Defaulting to no-operation (NOP) logger implementation
[INFO] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] WARNING: An illegal reflective access operation has occurred
[INFO] WARNING: Illegal reflective access by org.github.jamm.MemoryMeter (file:/Users/raj.srinivasan/.m2/repository/com/github/jbellis/jamm/0.3.0/jamm-0.3.0.jar) to field java.util.concurrent.ConcurrentSkipListMap.comparator
[INFO] WARNING: Please consider reporting this to the maintainers of org.github.jamm.MemoryMeter
[INFO] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[INFO] WARNING: All illegal access operations will be denied in a future release
[INFO] Cassandra cluster "Test Cluster" started.
[INFO] Running /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/src/main/deploy/init/cassandra-conf/AerFrameCluster.script...
[INFO] setting cqlversion: 3.4.0
[INFO] Finished /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/src/main/deploy/init/cassandra-conf/AerFrameCluster.script.
[INFO] Cassandra started in 7.8s
[INFO] 
[INFO] --- cassandra-maven-plugin:3.6:flush (start-cassandra) @ aerframe-core ---
[DEBUG] Configuring mojo org.codehaus.mojo:cassandra-maven-plugin:3.6:flush from plugin realm ClassRealm[plugin>org.codehaus.mojo:cassandra-maven-plugin:3.6, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@799f7e29]
[DEBUG] Configuring mojo 'org.codehaus.mojo:cassandra-maven-plugin:3.6:flush' with basic configurator -->
[DEBUG]   (f) addMainClasspath = true
[DEBUG]   (f) addTestClasspath = true
[DEBUG]   (f) cassandraDir = /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra
[DEBUG]   (f) classesDirectory = /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/classes
[DEBUG]   (f) jmxPort = 17199
[DEBUG]   (f) listenAddress = 127.0.0.1
[DEBUG]   (f) logLevel = ERROR
[DEBUG]   (f) maxMemory = 512
[DEBUG]   (f) nativeTransportPort = 9042
[DEBUG]   (f) pluginArtifact = org.codehaus.mojo:cassandra-maven-plugin:maven-plugin:3.6
[DEBUG]   (f) pluginDependencies = [org.codehaus.mojo:cassandra-maven-plugin:maven-plugin:3.6:, org.apache.cassandra:cassandra-all:jar:3.5:compile, org.xerial.snappy:snappy-java:jar:1.1.1.7:compile, net.jpountz.lz4:lz4:jar:1.3.0:compile, com.ning:compress-lzf:jar:0.8.4:compile, com.google.guava:guava:jar:18.0:compile, commons-cli:commons-cli:jar:1.1:compile, commons-codec:commons-codec:jar:1.2:compile, org.apache.commons:commons-lang3:jar:3.1:compile, org.apache.commons:commons-math3:jar:3.2:compile, com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:jar:1.4:compile, org.antlr:antlr:jar:3.5.2:compile, org.antlr:ST4:jar:4.0.8:compile, org.antlr:antlr-runtime:jar:3.5.2:compile, org.slf4j:slf4j-api:jar:1.7.7:compile, org.slf4j:log4j-over-slf4j:jar:1.7.7:compile, org.slf4j:jcl-over-slf4j:jar:1.7.7:compile, org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile, com.googlecode.json-simple:json-simple:jar:1.1:compile, com.boundary:high-scale-lib:jar:1.0.6:compile, org.yaml:snakeyaml:jar:1.11:compile, org.mindrot:jbcrypt:jar:0.3m:compile, io.dropwizard.metrics:metrics-core:jar:3.1.0:compile, com.addthis.metrics:reporter-config3:jar:3.0.0:compile, com.addthis.metrics:reporter-config-base:jar:3.0.0:compile, org.hibernate:hibernate-validator:jar:4.3.0.Final:compile, javax.validation:validation-api:jar:1.0.0.GA:compile, org.jboss.logging:jboss-logging:jar:3.1.0.CR2:compile, com.thinkaurelius.thrift:thrift-server:jar:0.3.7:compile, com.lmax:disruptor:jar:3.0.1:compile, com.clearspring.analytics:stream:jar:2.5.2:compile, it.unimi.dsi:fastutil:jar:6.5.7:compile, org.apache.thrift:libthrift:jar:0.9.2:compile, org.apache.httpcomponents:httpclient:jar:4.2.5:compile, org.apache.httpcomponents:httpcore:jar:4.2.4:compile, org.apache.cassandra:cassandra-thrift:jar:3.5:compile, com.carrotsearch:hppc:jar:0.5.4:compile, de.jflex:jflex:jar:1.6.0:compile, org.apache.ant:ant:jar:1.7.0:compile, org.apache.ant:ant-launcher:jar:1.7.0:compile, net.mintern:primitive:jar:1.0:compile, com.github.rholder:snowball-stemmer:jar:1.3.0.581.1:compile, com.googlecode.concurrent-trees:concurrent-trees:jar:2.4.0:compile, net.java.dev.jna:jna:jar:4.0.0:compile, com.github.jbellis:jamm:jar:0.3.0:compile, io.netty:netty-all:jar:4.0.23.Final:compile, joda-time:joda-time:jar:2.4:compile, org.fusesource:sigar:jar:1.6.4:compile, org.eclipse.jdt.core.compiler:ecj:jar:4.4.2:compile, org.caffinitas.ohc:ohc-core:jar:0.4.3:compile, org.apache.maven:maven-project:jar:2.2.1:compile, org.apache.maven:maven-settings:jar:2.2.1:compile, org.apache.maven:maven-profile:jar:2.2.1:compile, org.apache.maven:maven-plugin-registry:jar:2.2.1:compile, org.codehaus.plexus:plexus-interpolation:jar:1.11:compile, org.apache.maven.shared:maven-filtering:jar:1.0-beta-4:compile, org.apache.maven:maven-monitor:jar:2.0.6:compile, org.sonatype.plexus:plexus-build-api:jar:0.0.4:compile, org.apache.maven:maven-model:jar:2.2.1:compile, org.apache.maven:maven-artifact:jar:2.2.1:compile, org.apache.maven:maven-artifact-manager:jar:2.2.1:compile, org.apache.maven:maven-repository-metadata:jar:2.2.1:compile, backport-util-concurrent:backport-util-concurrent:jar:3.1:compile, org.apache.maven:maven-core:jar:2.2.1:compile, org.apache.maven:maven-plugin-parameter-documenter:jar:2.2.1:compile, org.apache.maven.reporting:maven-reporting-api:jar:2.2.1:compile, org.apache.maven.doxia:doxia-sink-api:jar:1.1:compile, org.apache.maven.doxia:doxia-logging-api:jar:1.1:compile, org.apache.maven:maven-error-diagnostics:jar:2.2.1:compile, org.apache.maven:maven-plugin-descriptor:jar:2.2.1:compile, org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile, classworlds:classworlds:jar:1.1:compile, org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile, org.sonatype.plexus:plexus-cipher:jar:1.4:compile, org.apache.maven:maven-plugin-api:jar:2.2.1:compile, org.codehaus.plexus:plexus-utils:jar:2.0.5:compile, org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile, org.apache.commons:commons-exec:jar:1.1:compile, org.apache.maven:maven-toolchain:jar:2.0.9:compile, org.cassandraunit:cassandra-unit:jar:1.0.3.1:compile, org.hamcrest:hamcrest-all:jar:1.1:compile, com.sun.xml.bind:jaxb-impl:jar:2.2.4-1:compile, javax.xml.bind:jaxb-api:jar:2.2.3:compile, javax.xml.stream:stax-api:jar:1.0-2:compile, javax.activation:activation:jar:1.1:compile, me.prettyprint:hector-core:jar:1.0-3:compile, commons-pool:commons-pool:jar:1.5.3:compile, com.github.stephenc.eaio-uuid:uuid:jar:3.2.0:compile, com.ecyrd.speed4j:speed4j:jar:0.9:compile, commons-lang:commons-lang:jar:2.6:compile]
[DEBUG]   (f) project = MavenProject: com.aeris.aerframe:aerframe-core:1.0.0 @ /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/pom.xml
[DEBUG]   (f) rpcAddress = 127.0.0.1
[DEBUG]   (f) rpcPort = 19160
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@733ec58b
[DEBUG]   (f) skip = false
[DEBUG]   (f) startNativeTransport = false
[DEBUG]   (f) stopKey = cassandra-maven-plugin
[DEBUG]   (f) stopPort = 18081
[DEBUG]   (f) storagePort = 17000
[DEBUG]   (f) testClassesDirectory = /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/test-classes
[DEBUG] -- end configuration --
**[DEBUG] Executing command line: java -jar /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/bin/nodetool.jar --host 127.0.0.1 --port 17199 flush
[INFO] Error: Unable to access jarfile /Users/raj.srinivasan/workspace-j11/aerframe/aerframe-core/target/cassandra/bin/nodetool.jar**
[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:3.6:flush (start-cassandra) on project aerframe-core: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:3.6:flush (start-cassandra) on project aerframe-core: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
    at org.codehaus.mojo.cassandra.FlushCassandraMojo.execute (FlushCassandraMojo.java:72)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:377)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:160)
    at org.codehaus.mojo.cassandra.FlushCassandraMojo.execute (FlushCassandraMojo.java:67)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by rajsrini** [comment]
POM

 <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cassandra-maven-plugin</artifactId>
                <version>${cassandra-maven-plugin.version}</version>
                <configuration>
                    <addMainClasspath>true</addMainClasspath>
                    <addTestClasspath>true</addTestClasspath>
                    <rpcPort>19160</rpcPort>
                    <jmxPort>17199</jmxPort>
                    <storagePort>17000</storagePort>
                    <stopPort>18081</stopPort>
                    <script>${basedir}/src/main/deploy/init/cassandra-conf/AerFrameCluster.script</script>
                </configuration>
                <executions>
                    <execution>
                        <id>start-cassandra</id>
                        <goals>
                            <goal>start</goal>
                            <goal>flush</goal>
                            <goal>cleanup</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                    </execution>
                    <execution>
                        <id>stop-cassandra</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <phase>post-integration-test</phase>
                    </execution>
                </executions>
            </plugin>

**Comment by rajsrini** [comment]
POM Section

===

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cassandra-maven-plugin</artifactId>
                <version>${cassandra-maven-plugin.version}</version>
                <configuration>
                    <addMainClasspath>true</addMainClasspath>
                    <addTestClasspath>true</addTestClasspath>
                    <rpcPort>19160</rpcPort>
                    <jmxPort>17199</jmxPort>
                    <storagePort>17000</storagePort>
                    <stopPort>18081</stopPort>
                    <script>${basedir}/src/main/deploy/init/cassandra-conf/AerFrameCluster.script</script>
                </configuration>
                <executions>
                    <execution>
                        <id>start-cassandra</id>
                        <goals>
                            <goal>start</goal>
                            <goal>flush</goal>
                            <goal>cleanup</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                    </execution>
                    <execution>
                        <id>stop-cassandra</id>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <phase>post-integration-test</phase>
                    </execution>
                </executions>
            </plugin>

**Comment by slachiewicz** [comment]
Cassandra 3.x doesn't support Java 11
