### ISSUE TITLE
Any chance of a release?

### ISSUE THREAD

**Issue by ajs6f** [mojohaus/cassandra-maven-plugin#33]
There have been five commits (and several years) since the release of 3.6. Is it possible any longer to release from this codebase? Thanks for any info or insight into what is possible!

**Comment by ajweave** [comment]
Closed with no comment.  What is the future of this project?  Is a release with support for Cassandra 4 planned?

**Comment by slachiewicz** [comment]
Hi, sorry - no ETA yet

**Comment by olamy** [comment]
> Closed with no comment. What is the future of this project? Is a release with support for Cassandra 4 planned?
I'm happy to release current master in few days.

But to be honest I do not see much chance of new features here (such cassandra version upgrade) as it's very easy now to use https://www.testcontainers.org/modules/databases/cassandra/
Or maybe having the plugin using internally testcontainers?

**Comment by olamy** [comment]
release 3.7 done
