### ISSUE TITLE
Add support for CQL3

### ISSUE THREAD

**Issue by Sandmania** [mojohaus/cassandra-maven-plugin#9]
Currenlty only CQL versions from 1.2.1 to 2.0 are supported. Support for CQL3 should be added.
See: 
http://www.datastax.com/dev/blog/whats-new-in-cql-3-0
and
http://www.datastax.com/dev/blog/thrift-to-cql3

**Comment by dvsekhvalnov** [comment]
+1 Is there are any plans for?
